//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_Real_Estate2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int Id { get; set; }
        public string Suburb { get; set; }
        public string Location { get; set; }
        public string Number_of_Rooms { get; set; }
        public string Floor_Area { get; set; }
        public string Land_Area { get; set; }
        public string RV { get; set; }
        public string Email { get; set; }
        public string Property_Type { get; set; }
    }
}
