//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_Real_Estate2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        public int Id { get; set; }
        public string Frist_name { get; set; }
        public string Last_name { get; set; }
        public string Address { get; set; }
        public string Phone_number { get; set; }
        public string Email_address { get; set; }
    }
}
